spring.application.name=avia1
#??????????? ? ??
spring.datasource.url=jdbc:mysql://localhost:3306/Avia
spring.datasource.username=root
spring.datasource.password=Diplom26

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.security.user.name=root
spring.security.user.password=Diplom26